insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Ballyea',52.82802,-9.10955,1,'http://www.gaainfo.com/graphics/gaa_versions/midi/ak.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Banner',52.89684,-8.993,1,'http://www.gaainfo.com/graphics/gaa_versions/midi/by.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Broadford',52.80681,-8.63972,1,'http://www.gaainfo.com/graphics/gaa_versions/midi/gl.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Clonboney',52.89192,-9.37348,1,'http://www.gaainfo.com/graphics/gaa_versions/midi/gl.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Clonlara',52.72397,-8.55449,1,'http://www.gaainfo.com/graphics/midicrest/05/midicrest_05_009.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Coolmeen',52.65913,-9.21392,1,'http://www.gaainfo.com/graphics/gaa_versions/midi/ak.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Corofin',52.94564,-9.07183,1,'http://www.gaainfo.com/graphics/gaa_versions/midi/rw.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Crusheen',52.93904,-8.8979,1,'http://www.gaainfo.com/graphics/gaa_versions/midi/rw.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Éire Óg, Inis',52.84633,-8.98617,1,'http://www.gaainfo.com/graphics/midicrest/05/midicrest_05_017.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Ennistymon',52.93938,-9.29327,1,'http://www.gaainfo.com/graphics/midicrest/05/midicrest_05_019.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Kildysart',52.66982,-9.10689,1,'http://www.gaainfo.com/graphics/gaa_versions/midi/bk.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Kilkee Bealatha',52.67909,-9.64896,1,'http://www.gaainfo.com/graphics/gaa_versions/midi/bw.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Killimer',52.6152,-9.4091,1,'http://www.gaainfo.com/graphics/gaa_versions/midi/gl.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Kilmihil',52.72044,-9.32593,1,'http://www.gaainfo.com/graphics/gaa_versions/midi/gl.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Kilnamona',52.87291,-9.0778,1,'http://www.gaainfo.com/graphics/gaa_versions/midi/gw.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Kilrush Shamrocks',52.64051,-9.48468,1,'http://www.gaainfo.com/graphics/gaa_versions/midi/gw.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Lissycasey',52.74284,-9.16286,1,'http://www.gaainfo.com/graphics/gaa_versions/midi/mw.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Newmarket On Fergus',52.76087,-8.8982,1,'http://www.gaainfo.com/graphics/midicrest/05/midicrest_05_037.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('OCallaghans Mills',52.84283,-8.68401,1,'http://www.gaainfo.com/graphics/gaa_versions/midi/bl.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Ruan',52.92872,-8.99171,1,'http://www.gaainfo.com/graphics/gaa_versions/midi/by.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Shannon Gaels',52.70604,-9.09256,1,'http://www.gaainfo.com/graphics/midicrest/05/midicrest_05_045.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Sixmilebridge',52.74164,-8.77709,1,'http://www.gaainfo.com/graphics/midicrest/05/midicrest_05_047.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('St. Josephs, Doora-Barefield',52.88695,-8.95008,1,'http://www.gaainfo.com/graphics/gaa_versions/midi/mw.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('St. Senans',52.67845,-9.64707,1,'http://www.gaainfo.com/graphics/gaa_versions/midi/bw.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Tulla',53.07304,-8.9442,1,'http://www.gaainfo.com/graphics/midicrest/05/midicrest_05_053.jpg');
insert into location ([Name],[LatX],[LatY],[CountyID],[Crest]) values ('Wolfe Tones, Na Sionna',52.7126,-8.8828,1,'http://www.gaainfo.com/graphics/midicrest/05/midicrest_05_055.jpg')